### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by pangda72** [bubbliiiing/pspnet-pytorch#12]
你好，前辈，当我运行pspnet.py的时候，发生了一个错误;
#==============================================================
Downloading: "http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet50-imagenet.pth" to ./model_data\resnet50-imagenet.pth
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/models/1.py", line 167, in <module>
    model = PSPNet(num_classes=2,downsample_factor=8).cuda()
  File "C:/Users/lenovo/Desktop/models/1.py", line 108, in __init__
    self.backbone = Resnet(downsample_factor, pretrained)
  File "C:/Users/lenovo/Desktop/models/1.py", line 16, in __init__
    model = resnet50(pretrained)
  File "C:\Users\lenovo\Desktop\models\resnet50.py", line 137, in resnet50
    model.load_state_dict(load_url(model_urls['resnet50']), strict=False)
  File "C:\Users\lenovo\Desktop\models\resnet50.py", line 132, in load_url
    return model_zoo.load_url(url,model_dir=model_dir)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\hub.py", line 461, in load_state_dict_from_url
    hash_prefix = HASH_REGEX.search(filename).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
#====================================================================
我不知道该如何解决这个问题，请问前辈可以帮助我吗？期待得到您的恢复，非常感谢。

**Comment by bubbliiiing** [comment]
你运行pspnet.py吗

**Comment by pangda72** [comment]
> 你运行pspnet.py吗

是的，我想打印下网络的结构然后就报这个错误

**Comment by bubbliiiing** [comment]
你应该运行test.py

**Comment by pangda72** [comment]
> 你应该运行test.py
好的，谢谢你。
